### ISSUE TITLE
Incompatible with Vanillafix

### ISSUE THREAD

**Issue by Sunconure11** [grondag/Pyroclasm#13]
https://pastebin.com/riXP0Fit

**Comment by grondag** [comment]
Yup. Thank you for the log. 

If it is open source I will look at what they are patching and see if there any way to resolve.

**Comment by grondag** [comment]
Should be fixable but wow, the Mixins framework is impressive. I'd heard of it but hadn't checked it out yet.

This bug is in the Acuity API and I hadn't planned on updating that until 1.13 but if Mixins will be ported then maybe it makes sense to switch now.

Hmmmm....

**Comment by grondag** [comment]
Okay - after some looking it isn't obvious how to fix this.  I'm not patching BufferBuilder at all.  I'm re-rerouting calls to the BufferBuilder initializer in order to instantiate a sub class of it. 

I'm guessing that MixIn doesn't actually patch the BufferBuilder constructor but instead looks for calls to it and patches those, thus the conflict.  If that's correct, then this will likely not be an easy fix.

It might be best to simply reimplement this using Mixin, but that will take more discovery and consideration.

If anyone more familiar with Mixins can help educate me here that might make it go faster.

Update: A helpful person on Reddit pointed out VanillaFix crash fixes can be disabled and that prevents this problem.  Would still like to resolve but less urgent now.

**Comment by Sunconure11** [comment]
@robijnvogel @zombieHDgaming

**Comment by grondag** [comment]
Will be addressed in 1.13, probably by switching to MixIn framework

**Comment by grondag** [comment]
Fixed in the next build of Acuity.  Decided to port to Mixin framework now.  Will only make 1.13 easier.
