### ISSUE TITLE
tessellating block issue 

### ISSUE THREAD

**Issue by Vagueness** [grondag/Pyroclasm#22]
The items in the creative menu don't show - besides the seismometer - and when a volcano reaches a certain point in its eruption ( ie: the lava reaches the surface ), the game crashes with an error stating ' exceptional tessellating block error '. 

Is there anyway to overcome this issue currently ?

**Comment by grondag** [comment]
Hmmm, not currently supporting this for 1.12 but if you post a log I'll take a look.  Also - what items were you expecting in the creative menu?

**Comment by Vagueness** [comment]
It isn't ? Hm, odd - it's on 9Minecraft staying it's supported for 1.12.2.
as for items, none show up besides the seismometer - items such as cool basalt should appear in the menu, correct ?

Here's the crash message: 
`The game crashed whilst tesselating block model
Error: java.lang.ArrayIndexOutOfBoundsException: 28`

[crash log.txt](https://github.com/grondag/Pyroclasm/files/2922407/crash.log.txt)

**Comment by grondag** [comment]
I only distribute my mods via CurseForge (for example, https://minecraft.curseforge.com/projects/acuity) and can't recommend or support 9Minecraft.

Thank you for providing the crash log.  Unfortunately, it's not obvious what's happening. Best advice I can offer is to remove other mods and delete the configs for Exotic Matter, Acuity and Pyroclasm to make sure they are reset to defaults.

Even so, Pyroclasm and Acuity were/are both highly experimental mods, and not ready for a stable play experience. That's why I never released anything other than an alpha version.  I am working newer versions that may be more playable, but I have no planned release date.

**Comment by Redd56** [comment]
i turned shaders and it immediately crashed

**Comment by Redd56** [comment]
same exact array out of bound exception:28
but only happened once i turned on shaders

**Comment by Yenlon** [comment]
Guys, I found the solution: Deinstall the way too much overrated Optifine! I created a modpack with pyroclasm and many many other mods and only Opifine seems after tedious testings to conflict with pyroclasm and create the exact same error message. So all you have to do is to get rid of this 'performance boosting' crap...
